repos:
  - hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: [ '--maxkb=1500' ]
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0

  - hooks:
      - id: isort
    repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v5.8.0'
  - hooks:
      - id: black
        language_version: python3
    repo: https://github.com/psf/black
    rev: 20.8b1
  - hooks:
      - id: gitlint
    repo: https://github.com/jorisroovers/gitlint
    rev: v0.15.1
  - hooks:
      - id: flake8
    repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.1
